# NUMPY

In [1]:
import numpy as np

In [2]:
list1 = [1,2,3,4,5,6]
arr = np.array(list1)

In [3]:
#type
type(arr)

numpy.ndarray

In [4]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
#Shape
arr.shape

(6,)

In [6]:
ls1 = [1,2,3,4,5,6]
ls2 = [11,22,34,45,56,67]
ls3 =[3,4,5,6,7,8]
ar = np.array([ls1,ls2,ls3])

In [7]:
ar

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 34, 45, 56, 67],
       [ 3,  4,  5,  6,  7,  8]])

In [8]:
type(ar)

numpy.ndarray

In [12]:
np.shape(ar)


(3, 6)

In [39]:
#reshape
ar.shape

(3, 6)

In [13]:
ar.reshape(6,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 22, 34],
       [45, 56, 67],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [14]:
ar

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 34, 45, 56, 67],
       [ 3,  4,  5,  6,  7,  8]])

In [18]:
#indexing
#accessing elements
ar[2]

array([3, 4, 5, 6, 7, 8])

In [19]:
ar[1:,2:]

array([[34, 45, 56, 67],
       [ 5,  6,  7,  8]])

In [20]:
ar[:2,4:]

array([[ 5,  6],
       [56, 67]])

In [21]:
ar[1:3,2:5]

array([[34, 45, 56],
       [ 5,  6,  7]])

In [30]:
#range
ar1 = np.arange(0,12)
ar2 = np.arange(0,12,3)

In [34]:
ar1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
#1d
ar1.shape

(12,)

In [83]:
#2d
ar1 = ar1.reshape(3,4)
ar1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
ar2

array([0, 3, 6, 9])

In [43]:
ar2.reshape(2,2)

array([[0, 3],
       [6, 9]])

In [44]:
ar1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
#copy
ar_first = np.arange(0,5)

In [47]:
ar_first

array([0, 1, 2, 3, 4])

In [48]:
ar_sec = ar_first

In [49]:
ar_sec

array([0, 1, 2, 3, 4])

In [50]:
ar_sec[2:4] = 200
ar_sec

array([  0,   1, 200, 200,   4])

In [51]:
# reflecting in orginal array even though we have changed in second day array because of memory
ar_first

array([  0,   1, 200, 200,   4])

In [52]:
#copy function
ar_sec = ar_first.copy()
ar_sec[:2] = 200
ar_sec

array([200, 200, 200, 200,   4])

In [54]:
# values are not reflecting in first array due to copy function
ar_first

array([  0,   1, 200, 200,   4])

In [57]:
#linspace (equal distribution)
ar_lin = np.linspace(1,10,10)
ar_lin


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [56]:
ar_lin1 = np.linspace(1,10,50)
ar_lin1

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [58]:
#conditions
a = np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [59]:
a < 3


array([ True,  True,  True, False, False])

In [61]:
# to get the value 
a[a<3]

array([0, 1, 2])

In [62]:
a*2

array([0, 2, 4, 6, 8])

In [63]:
a/2

array([0. , 0.5, 1. , 1.5, 2. ])

In [65]:
#ones
a_one = np.ones(5)
a_one

array([1., 1., 1., 1., 1.])

In [66]:
#zeros
a_zero = np.zeros(6)
a_zero

array([0., 0., 0., 0., 0., 0.])

In [71]:
#ones in 2d (by default values are in float)
a_ones = np.ones((2,3))
a_ones


array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
#int
a_int =  np.ones((2,3),dtype=int)
a_int

array([[1, 1, 1],
       [1, 1, 1]])

In [75]:
#random
ar_rand = np.random.rand(2,2)
ar_rand

array([[0.94479446, 0.27553934],
       [0.48821122, 0.94773368]])

In [76]:
#random based on normal distribution
ar_nrand = np.random.randn(4,5)
ar_nrand

array([[-1.41901554, -0.14748205, -1.17958515, -0.79755029,  0.00788989],
       [ 1.77357822,  0.02861806,  1.53851273, -0.28477659, -0.35878909],
       [-0.00826175,  1.10020019, -1.42675586,  0.76705653,  1.22281692],
       [ 1.61656599,  1.88154445,  0.83895335,  1.3262173 , -0.50634105]])

In [79]:
#randint
a_randint = np.random.randint(0,20,5)
a_randint

array([12, 16, 10,  8,  3])

In [81]:
a_randint1 = np.random.randint(0,20,12).reshape(3,4)
a_randint1

array([[ 4,  1,  3,  1],
       [14, 12,  2,  4],
       [ 6, 11,  9,  7]])